### ISSUE TITLE
Log search rules created in AlzMonitoring-rg, other rules in rg-alz-monitor

### ISSUE THREAD

**Issue by ThojoUno** [Azure/alz-monitor#211] opened 2023-07-21 03:51 UTC
It looks like the newer Log search rules are created in an entirely different resource group than other monitoring items, that are created in rg-alz-monitor resource group.

**Comment by paulgrimley** [comment] 2023-07-21 10:43
Thanks for highlighting, looking into this.

**Comment by arjenhuitema** [comment] 2023-07-25 11:40
Thank you @ThojoUno. Underlying root cause will be fixed as soon as the PR is merged. After the merge you may need to remove the Landing Zone Initiative Assignment and Definition, afterwards redeploy and reassign the landing zone initiative. You also may want to cleanup already created resources/ resource groups that were not created in the desired location, as removing the assignment and definition will not clear that up automatically. 

After removing the assignment/ definition, you can for example use Azure CLI from a PowerShell command prompt and run the following commands to deploy and assign the LZ initiative.

**Redeploy LZ Initiative:**
`az deployment mg create --template-file ./src/resources/Microsoft.Authorization/policySetDefinitions/ALZ-MonitorLandingZone.json --location $location --management-group-id $pseudoRootManagementGroup
`

**Reassign:** 
`az deployment mg create --template-file ./infra-as-code/bicep/assign_initiatives_landingzones.bicep --location $location --management-group-id $LZManagementGroup --parameters ./infra-as-code/bicep/parameters-complete-landingzones.json`

Please let me know you if you have any questions.

**Closed** 2023-07-25 12:10 UTC
